---
- hosts: all
#  become: true
  vars_files:
    - vars/default.yml

# tasks file for deploy-from-git
  tasks:
    - name: pull from git
      git:
        repo: "{{ git_url }}"
        accept_hostkey: yes
        dest: "{{ git_repo_path }}"
        key_file: "{{ key_file }}"
        update: yes
#        version: event_agenda

    - name: Set HTTPS remote URL
      git_config:
        name: remote.origin.url
        value: "{{ git_url_orig }}"
        scope: local
        repo: "{{ git_repo_path }}"
